version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: disworse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
