services:
    pg:
        image: postgres:15-alpine
        container_name: postgres-dev
        restart: always
        ports:
            - 5432:5432

    cache:
        image: redis:7.2.4-alpine
        container_name: cache-dev
        restart: always
        ports:
            - 6379:6379
