/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as NotFoundImport } from './app/routes/not-found'

// Create Virtual Routes

const GraphqlTestLazyImport = createFileRoute('/graphql-test')()
const IndexLazyImport = createFileRoute('/')()
const AppIndexLazyImport = createFileRoute('/app/')()

// Create/Update Routes

const GraphqlTestLazyRoute = GraphqlTestLazyImport.update({
  path: '/graphql-test',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./app/routes/graphql-test.lazy').then((d) => d.Route),
)

const NotFoundRoute = NotFoundImport.update({
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./app/routes/index.lazy').then((d) => d.Route))

const AppIndexLazyRoute = AppIndexLazyImport.update({
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./app/routes/app/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/graphql-test': {
      id: '/graphql-test'
      path: '/graphql-test'
      fullPath: '/graphql-test'
      preLoaderRoute: typeof GraphqlTestLazyImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/not-found': typeof NotFoundRoute
  '/graphql-test': typeof GraphqlTestLazyRoute
  '/app': typeof AppIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/not-found': typeof NotFoundRoute
  '/graphql-test': typeof GraphqlTestLazyRoute
  '/app': typeof AppIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/not-found': typeof NotFoundRoute
  '/graphql-test': typeof GraphqlTestLazyRoute
  '/app/': typeof AppIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/not-found' | '/graphql-test' | '/app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/not-found' | '/graphql-test' | '/app'
  id: '__root__' | '/' | '/not-found' | '/graphql-test' | '/app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  NotFoundRoute: typeof NotFoundRoute
  GraphqlTestLazyRoute: typeof GraphqlTestLazyRoute
  AppIndexLazyRoute: typeof AppIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  NotFoundRoute: NotFoundRoute,
  GraphqlTestLazyRoute: GraphqlTestLazyRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/not-found",
        "/graphql-test",
        "/app/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/graphql-test": {
      "filePath": "graphql-test.lazy.tsx"
    },
    "/app/": {
      "filePath": "app/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
